version: '2'
services:
  learn-api:
    build: .
    links:
    - learn-mongo:mongo
    depends_on:
    - learn-mongo
    ports:
    - 8080:8080
  learn-mongo:
    image: mongo:latest
    container_name: "learn-mongo"
    environment:
      MONGODB_USER: "user"
      MONGODB_DATABASE: "learn"
      MONGODB_PASS: "sql"
    ports:
    - 27017
